### ISSUE TITLE
No module named networkx

### ISSUE THREAD

**Issue by kloss07** [sowdust/ffff#1]
What am I doing wrong?
python3 ffff.py -fu user@gmail.com -fp passw -t 6 -p 7 -o results.csv -g graph.gexf -q  ./geckodriver

output
Traceback (most recent call last):
  File "ffff.py", line 4, in <module>
    import networkx as nx, builtins
ModuleNotFoundError: No module named 'networkx'

I use parrotsec os, done everything as described in README

Thanks for any suggestions

**Comment by sowdust** [comment]
Hello, it looks like you are missing the python library "networkx".
You can install it by typing: 
`pip3 install networkx` (or `pip install networkx`)
Make sure you also install the other required libraries: selenium and argparse.
You should be able to install them all by typing `pip3 install -r requirements.txt` as shown in the README.
