### ISSUE TITLE
[Error] Login Check

### ISSUE THREAD

**Issue by swallaaa** [sowdust/ffff#10]
I experienced this error while running. I presume a change Facebook did broke your validator.

ffff.py v. 0.2 - FFFF: FFFF Finds Facebook Friends

by sowdust

Loaded 10 facebook ids to use for pivoting.
Graph Output file not specified. Results will be stored in [redacted]-friends.gexf

[!] Not logged in. Did you use valid credentials?

**Comment by sowdust** [comment]
fixed here https://github.com/sowdust/ffff/commit/c0f0bd71cc62b4f399b1f7e54e0442926a3adb8c
