### ISSUE TITLE
...

### ISSUE THREAD

**Issue by VasilEmilov** [sowdust/ffff#12]

**Comment by sowdust** [comment]
hi, don't know why you deleted the issue, but you are right. check_login function is now updated to work with the new change in the interface.

**Comment by VasilEmilov** [comment]
At first I thought there is bigger issue because I removed the check_login to continue with the process and still ran into problems, but it was on my side only.

**Comment by sowdust** [comment]
Ok! Thanks to your issue though the check login is fixed as well ;)
