### ISSUE TITLE
Finito

### ISSUE THREAD

**Issue by skalierer** [sowdust/ffff#18]
I think Facebook has just deprecated this endpoint.

**Comment by Seb2lyon** [comment]
Indeed @skalierer
I try directly with the URL : www.facebook.com/browse/mutual_friends/?uid=ID1&node=ID2
No more results provided in the FB page.

**Comment by zeluxo86** [comment]
That's correct. It doesn't work anymore. It was a great tool!

**Comment by sowdust** [comment]
I confirm. The project is currently discontinued. If new ways to do the same thing emerge, I will consider updating the tool.
