### ISSUE TITLE
Inspired implementation in NodeJS

### ISSUE THREAD

**Issue by t-rekttt** [sowdust/ffff#2]
Well, no issue here, just want to say I'm inspired by your work and I made another implementation of my own in NodeJS. Here it is:
https://github.com/t-rekttt/fb_friends_graph
And thanks for your awesome blog post, keep it up 👍 
Hope that message through here won't bother you

**Comment by sowdust** [comment]
Great stuff, I'm happy you found it useful ;)
thanks for sharing your work!
