### ISSUE TITLE
login check fails (was: program crashes)

### ISSUE THREAD

**Issue by jbdu94** [sowdust/ffff#7]
Hello Sir, 

I fixed the geckodriver error, thx to you (I copied the geckodriver in the same folder of the python code), now I am having another kind of problem.
I successfully connect in facebook with your program, but then your program crashes and says: 
[!] Not logged in. Did you use valid credentials?

No other error.
Of course my credentials are correct because I am connected, in only the firefox popup opened by your program.

Any idea how to fix this?
I really want to use your program and see what I can obtain with it, if you could help, that would be awesome
Thanks a lot sir

**Comment by sowdust** [comment]
Hi jdbu96, thanks for noticing this. Facebook has recently changed the user interface and broke the piece of code that checked if the user is correctly logged in.
I have updated it to work with the new interface; it seems working on my side. Can you please confirm the new version is working for you too?

**Comment by jbdu94** [comment]
Yes Sir, it works now.
Thank you so much for your quick update
You rock !

And may I ask a last question? this time about fint.py
on the profile I check, it hasn't retrieved any data, however some public information is available (likes / comments), is it normal?

**Comment by sowdust** [comment]
The script fint.py, included in this repository, should do exactly this ;) (although I have not tested it in a while).

**Comment by swallaaa** [comment]
@sowdust 

This is broken again. Any quick fix?

ffff.py v. 0.2 - FFFF: FFFF Finds Facebook Friends

by sowdust

Loaded 10 facebook ids to use for pivoting.
Graph Output file not specified. Results will be stored in [redacted]-friends.gexf

[!] Not logged in. Did you use valid credentials?
