### ISSUE TITLE
fint.py URL incomplete

### ISSUE THREAD

**Issue by jbdu94** [sowdust/ffff#8]
Hello Sir

I tested fint.py
It connects succesfully on FB, then if we put target as ID,  it makes this https://mbasic.facebook.com//photos
it should be https://mbasic.facebook.com/PROFILE_NAME_HERE/photos

Even if I put target USER_PROFILE, it opens the right page but doesn't retrieve anything.
Somehow it doesnt retrieve the infos (names of Likers and Comment writers), dunno why, tried 3 times

Here is what the console says
```
Error while getting id of user USER_PROFILE
Selected target: USER_PROFILE (-1)
Getting photos links...  0 photos found
Getting stories links...  0 stories found
Retreiving users who have interacted... press Ctrl+C when you have enough
------------------------------------------------------------------------------
                                   STATISTICS
------------------------------------------------------------------------------
Most comments:

Most reactions:

Total:

[*] Storing users id in file resultfint.txt
[*] Found 0 comments and 0 reactions from 0 unique users
```

**Comment by sowdust** [comment]
Hi, can you confirm that your target user does not have a username (ie: when you visit his page in the url you get something like facebook.com/profile.php?id=...) instead of facebook.com/username)?

If so, this case needs to be implemented

**Comment by jbdu94** [comment]
Here are results

I removed the FB account given below, for privacy reason

`py.exe fint.py -fu email@myemail.com -fp my_fb_pass -t -censored- -o resultfint.txt -d geckodriver.exe`

It goes to:
`https://www.facebook.com/-censored-/`

then:
`https://mbasic.facebook.com//photos`

And nothing is collected



Now, I try like that:
`py.exe fint.py -fu email@myemail.com -fp my_fb_pass -t -censored- -o resultfint.txt -d geckodriver.exe`

It goes to :
`https://www.facebook.com/firstname.name.digit/`

Then:
`https://mbasic.facebook.com/firstname.name.digit/photos`

```
But nothing is collected in console

[!] Error while getting id of user firstname.name.digit
[*] Selected target: firstname.name.digit (-1)
[*] Getting photos links...  0 photos found
[*] Getting stories links...  0 stories found
[*] Retreiving users who have interacted... press Ctrl+C when you have enough
------------------------------------------------------------------------------
                                   STATISTICS
------------------------------------------------------------------------------
Most comments:

Most reactions:

Total:

[*] Storing users id in file resultfint.txt
[*] Found 0 comments and 0 reactions from 0 unique users
```

**Comment by sowdust** [comment]
Hi, I will need to look into this as soon as I have some time... it's probably because of the changes Facebook is making in its interface.

**Comment by jbdu94** [comment]
Please let me know when you fixed it.
I tried myself but without luck, their class have different names for each post, we cannot get likers by this method (or maybe you will be luckier)

**Comment by hpiedcoq** [comment]
I just submitted a PR for this.
