### ISSUE TITLE
Seems to not work on OpenSUSE?

### ISSUE THREAD

**Issue by tunnckoCore** [sowdust/ffff#9]
openSUSE Thumbleweed, Python 3+, installed `pip3 requirements` without errors, Gecko 0.26 (current latest release tag)... and errros with the following

```
charlike@suse:~/github/ffff> python3.8 ./ffff.py -t zzz -p ...pivots -q

./ffff.py v. 0.2 - FFFF: FFFF Finds Facebook Friends

by sowdust

Output file not specified. Results will be stored in zzz-friends.csv
Graph Output file not specified. Results will be stored in zzz-friends.gexf

Traceback (most recent call last):
File "./ffff.py", line 423, in <module>
main()
File "./ffff.py", line 388, in main
do_login(driver,usr,pwd)
File "./ffff.py", line 64, in do_login
driver.get('https://www.facebook.com')
File "/home/charlike/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
self.execute(Command.GET, {'url': url})
File "/home/charlike/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/home/charlike/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//www.facebook.com/&c=UTF-8&f=regular&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.facebook.com.
```

Before that it was failing to connect due to my 2FA, so I disabled it. It would be good to mention that in the docs tho :)

I'm not that on Python, but... seems like it still fails to login.

---

Do you know any other tools and/or browser extensions that does similar thing? I've seen there was something like "Facebook Friends Mapper" in 2015s and a ton of articles and videos are referencing it, but seems it's shut down from the Chrome Store haha.

**Comment by sowdust** [comment]
Hello, if you look at your stack trace it seems as if there is some issue with your selenium /network configuration. Last line indicates something about not being able to connect to facebook.com.
I suggest trying to run the script without the option "-q": this way a browser window will be opened and you can watch what the program is doing.

**Comment by tunnckoCore** [comment]
Yea, I tried that before posting too. It opened the browser, and shows the same error the browsery way, like I don't have internet... but that's not true.

**Comment by sowdust** [comment]
I am sorry but this seems to depend on your network configuration and not by ffff. Try looking at the browser configurations and to open different websites

**Comment by tunnckoCore** [comment]
Yup, it's most probably the NextDNS that I have configured on every level - OS, browser, router.
